# Generated by Django 2.2.5 on 2021-03-25 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20210301_0902'),
        ('shop_goods_detail', '0004_goods_color_goods_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_color_other_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_title', models.CharField(max_length=50, verbose_name='商品名稱')),
                ('goods_color_img_1', models.ImageField(null=True, upload_to='static/upload/images/goods_other_color_img')),
                ('goods_color_img_2', models.ImageField(null=True, upload_to='static/upload/images/goods_other_color_img')),
                ('goods_color_img_3', models.ImageField(null=True, upload_to='static/upload/images/goods_other_color_img')),
                ('goods_color_img_4', models.ImageField(null=True, upload_to='static/upload/images/goods_other_color_img')),
                ('goods_color_img_5', models.ImageField(null=True, upload_to='static/upload/images/goods_other_color_img')),
                ('goods_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_goods_detail.Goods_color', verbose_name='商品顏色編號')),
                ('goods_type', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType', verbose_name='商品主類別')),
                ('goods_type2', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType2', verbose_name='商品樣式')),
            ],
            options={
                'verbose_name': '商品其他顏色商品圖',
                'verbose_name_plural': '商品其他顏色商品圖',
                'db_table': 'Goods_color_other_img',
            },
        ),
    ]
