# Generated by Django 2.2.5 on 2021-03-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_goods_detail', '0007_remove_goods_color_other_img_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_color_other_img',
            name='goods_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='主商品編號', to='index.Goods'),
        ),
    ]
