# Generated by Django 2.2.5 on 2021-03-26 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_goods_detail', '0008_auto_20210325_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods_color_other_img',
            options={'verbose_name': '其他顏色商品圖', 'verbose_name_plural': '其他顏色商品圖'},
        ),
        migrations.AddField(
            model_name='goods_color_other_img',
            name='color',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='商品顏色', to='shop_goods_detail.Goods_color'),
        ),
        migrations.AlterField(
            model_name='goods_color_other_img',
            name='goods_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_goods_detail.Goods_color', verbose_name='商品顏色編號'),
        ),
    ]
