# Generated by Django 2.2.5 on 2021-03-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_goods_detail', '0021_remove_goods_color_goods_color_img_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_color',
            name='goods_color_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/images/goods_other_color_img', verbose_name='商品圖片1'),
        ),
        migrations.AddField(
            model_name='goods_color',
            name='goods_color_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/images/goods_other_color_img', verbose_name='商品圖片2'),
        ),
        migrations.AddField(
            model_name='goods_color',
            name='goods_color_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/images/goods_other_color_img', verbose_name='商品圖片3'),
        ),
        migrations.AddField(
            model_name='goods_color',
            name='goods_color_img_4',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/images/goods_other_color_img', verbose_name='商品圖片4'),
        ),
        migrations.AddField(
            model_name='goods_color',
            name='goods_color_img_5',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/images/goods_other_color_img', verbose_name='商品圖片5'),
        ),
        migrations.AlterField(
            model_name='goods_color',
            name='goods_color_img',
            field=models.ImageField(upload_to='static/upload/images/goods_color', verbose_name='商品圖片顏色'),
        ),
    ]
