# Generated by Django 2.2.5 on 2021-05-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0017_auto_20210416_2016'),
        ('index', '0016_auto_20210301_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_track_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Goods', verbose_name='追蹤商品')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_Member', verbose_name='會員名稱')),
            ],
            options={
                'verbose_name': '會員追蹤清單表',
                'verbose_name_plural': '會員追蹤清單表',
                'db_table': 'user_track_goods',
            },
        ),
    ]
