# Generated by Django 2.2.5 on 2021-03-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_name', models.CharField(max_length=40, verbose_name='國家')),
            ],
            options={
                'verbose_name': '國家表',
                'verbose_name_plural': '國家表',
                'db_table': 'Country',
            },
        ),
    ]
