# Generated by Django 2.2.5 on 2021-04-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '註冊國家表', 'verbose_name_plural': '註冊國家表'},
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=100, verbose_name='城市')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Country', verbose_name='國家')),
            ],
            options={
                'verbose_name': '國家地區表',
                'verbose_name_plural': '國家地區表',
                'db_table': 'City',
            },
        ),
    ]
