# Generated by Django 2.2.5 on 2021-04-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210401_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Member',
        ),
    ]
