# Generated by Django 2.2.5 on 2021-04-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_user_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_member',
            name='check_email_time',
            field=models.DateTimeField(null=True, verbose_name='信箱驗證成功時間'),
        ),
        migrations.AddField(
            model_name='user_member',
            name='registered_time',
            field=models.DateTimeField(null=True, verbose_name='註冊時間'),
        ),
    ]
