# Generated by Django 2.2.5 on 2021-04-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20210408_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_member',
            name='password',
            field=models.CharField(max_length=100, verbose_name='會員密碼'),
        ),
    ]
