# Generated by Django 2.2.5 on 2021-04-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20210408_2148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Member',
        ),
    ]
