# Generated by Django 2.2.5 on 2021-04-11 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_delete_user_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='會員帳號')),
                ('password', models.CharField(max_length=100, verbose_name='會員密碼')),
                ('realname', models.CharField(max_length=20, verbose_name='會員姓名')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='會員信箱')),
                ('birthday', models.DateField(verbose_name='會員生日日期')),
                ('phone_number', models.CharField(max_length=10, verbose_name='會員電話')),
                ('is_Active', models.BooleanField(default=False, verbose_name='帳號是否驗證成功')),
                ('registered_time', models.DateTimeField(null=True, verbose_name='註冊時間')),
                ('check_email_time', models.DateTimeField(null=True, verbose_name='信箱驗證成功時間')),
                ('authority', models.BooleanField(default=False, verbose_name='管理權限')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.City', verbose_name='城市')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Country', verbose_name='國家')),
            ],
            options={
                'verbose_name': '會員資訊',
                'verbose_name_plural': '會員資訊',
                'db_table': 'User_Member',
            },
        ),
    ]
