# Generated by Django 2.2.5 on 2021-04-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_user_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_member',
            old_name='check_email_time',
            new_name='check_emaill_time',
        ),
        migrations.AddField(
            model_name='user_member',
            name='send_emaill_time',
            field=models.DateTimeField(null=True, verbose_name='發送驗證信件時間'),
        ),
    ]
