# Generated by Django 2.2.5 on 2021-03-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20210301_0902'),
        ('shop_goods_detail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods_color',
            name='goods_id',
        ),
        migrations.AddField(
            model_name='goods_color',
            name='goods',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='index.Goods', verbose_name='商品型號'),
        ),
        migrations.AlterField(
            model_name='goods_color',
            name='goods_color_img',
            field=models.ImageField(upload_to='static/upload/images/goods_color', verbose_name='商品顏色路徑'),
        ),
    ]
