# Generated by Django 2.2.5 on 2021-03-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_goods_detail', '0006_auto_20210325_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods_color_other_img',
            name='color',
        ),
    ]
