# Generated by Django 2.2.5 on 2021-03-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_goods_detail', '0009_auto_20210326_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_color_other_img',
            name='goods_title',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='商品名稱', to='shop_goods_detail.Goods_color'),
        ),
    ]
