# Generated by Django 2.2.5 on 2021-03-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_goods_detail', '0010_auto_20210326_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_color',
            name='goods_color_img_1',
            field=models.ImageField(null=True, upload_to='static/upload/images/goods_other_color_img', verbose_name='商品圖片1'),
        ),
        migrations.AddField(
            model_name='goods_color',
            name='goods_color_img_2',
            field=models.ImageField(null=True, upload_to='static/upload/images/goods_other_color_img', verbose_name='商品圖片2'),
        ),
        migrations.AddField(
            model_name='goods_color',
            name='goods_color_img_3',
            field=models.ImageField(null=True, upload_to='static/upload/images/goods_other_color_img', verbose_name='商品圖片3'),
        ),
        migrations.AddField(
            model_name='goods_color',
            name='goods_color_img_4',
            field=models.ImageField(null=True, upload_to='static/upload/images/goods_other_color_img', verbose_name='商品圖片4'),
        ),
        migrations.AddField(
            model_name='goods_color',
            name='goods_color_img_5',
            field=models.ImageField(null=True, upload_to='static/upload/images/goods_other_color_img', verbose_name='商品圖片5'),
        ),
        migrations.DeleteModel(
            name='Goods_color_other_img',
        ),
    ]
