# Generated by Django 2.2.5 on 2021-03-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_goods_detail', '0017_auto_20210326_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods_color',
            name='goods_color_img_1',
        ),
    ]
