# Generated by Django 2.2.5 on 2021-05-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_info',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='訂單編號'),
        ),
    ]
