# Generated by Django 2.2.5 on 2021-05-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0005_auto_20210506_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='order_number',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='訂單編號'),
        ),
    ]
