# Generated by Django 2.2.5 on 2021-05-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0008_auto_20210506_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='訂單編號'),
        ),
    ]
