# Generated by Django 2.2.5 on 2021-05-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0011_order_info_order_info_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_info_detail',
            name='order_time',
            field=models.DateField(null=True, verbose_name='訂單日期'),
        ),
    ]
