# Generated by Django 2.2.5 on 2021-04-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210401_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='會員帳號')),
                ('password', models.CharField(max_length=20, verbose_name='會員密碼')),
                ('realname', models.CharField(max_length=20, verbose_name='會員姓名')),
                ('email', models.EmailField(max_length=50, verbose_name='會員信箱')),
                ('birthday', models.DateField(verbose_name='會員生日日期')),
                ('phone_number', models.CharField(max_length=10, verbose_name='會員電話')),
                ('is_Active', models.BooleanField(verbose_name='帳號是否驗證成功')),
                ('authority', models.BooleanField(default=False, verbose_name='管理權限')),
            ],
            options={
                'verbose_name': '會員資訊',
                'verbose_name_plural': '會員資訊',
                'db_table': 'User_Member',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '國家地區', 'verbose_name_plural': '國家地區'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '國家表', 'verbose_name_plural': '國家表'},
        ),
    ]
