# Generated by Django 2.2.5 on 2021-04-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_user_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Member',
        ),
    ]
