# Generated by Django 2.2.5 on 2021-02-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_goodstype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name': '商品主類別', 'verbose_name_plural': '商品主類別'},
        ),
    ]
