# Generated by Django 2.2.5 on 2021-02-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210223_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('GoodsType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType', verbose_name='主類別')),
            ],
            options={
                'verbose_name': '商品樣式類別',
                'verbose_name_plural': '商品樣式類別',
                'db_table': 'GoodsType2',
            },
        ),
    ]
