# Generated by Django 2.2.5 on 2021-02-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_goodstype2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='title',
            field=models.CharField(max_length=30, verbose_name='主類別'),
        ),
        migrations.AlterField(
            model_name='goodstype2',
            name='title',
            field=models.CharField(max_length=50, verbose_name='商品樣式類別'),
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='商品名稱')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('desc', models.CharField(max_length=200, null=True, verbose_name='商品敘述')),
                ('s_desc', models.CharField(max_length=100, null=True, verbose_name='商品簡述')),
                ('Images_url', models.ImageField(upload_to='images/goods_min')),
                ('like', models.IntegerField(verbose_name='愛心次數')),
                ('goods_put_on', models.DateField(verbose_name='商品上架日期')),
                ('goods_gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, verbose_name='商品種類性別')),
                ('GoodsType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType', verbose_name='主類別表')),
                ('GoodsType2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType2', verbose_name='商品樣式表')),
            ],
            options={
                'verbose_name': '主商品表',
                'verbose_name_plural': '主商品表',
                'db_table': 'Goods',
            },
        ),
    ]
