# Generated by Django 2.2.5 on 2021-02-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210223_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='Images_url',
            field=models.ImageField(upload_to='images/goods_min', verbose_name='圖片路徑'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品價格'),
        ),
    ]
