# Generated by Django 2.2.5 on 2021-04-18 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_user_cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Goods', verbose_name='商品編號'),
        ),
        migrations.AlterField(
            model_name='shop_user_cart',
            name='goods_color',
            field=models.CharField(max_length=20, verbose_name='商品顏色'),
        ),
        migrations.AlterField(
            model_name='shop_user_cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_Member', verbose_name='用戶名稱'),
        ),
    ]
