# Generated by Django 2.2.5 on 2021-04-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0003_shop_user_cart_goods_color_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_user_cart',
            name='goods_color_img_url',
            field=models.CharField(max_length=100, null=True, verbose_name='商品顏色小圖路徑'),
        ),
        migrations.AlterField(
            model_name='shop_user_cart',
            name='goods_img_url',
            field=models.CharField(max_length=100, verbose_name='商品圖'),
        ),
    ]
