# Generated by Django 2.2.5 on 2021-05-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0005_remove_shop_user_cart_goods_color_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chose_pay', models.CharField(max_length=50, verbose_name='支付配送方式')),
                ('send_price', models.IntegerField(verbose_name='運費金額')),
            ],
            options={
                'verbose_name': '支付方式表',
                'verbose_name_plural': '支付方式表',
                'db_table': 'Pay_Send',
            },
        ),
    ]
