# Generated by Django 2.2.5 on 2021-05-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0006_pay_send'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop_user_cart',
            options={'verbose_name': '用戶購物車商品表', 'verbose_name_plural': '用戶購物車商品表'},
        ),
    ]
