# Generated by Django 2.2.5 on 2021-02-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210224_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='GoodsType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType', verbose_name='主類別'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='GoodsType2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType2', verbose_name='商品樣式類別'),
        ),
    ]
