# Generated by Django 2.2.5 on 2021-02-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210224_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodstype2',
            name='GoodsType',
        ),
    ]
