# Generated by Django 2.2.5 on 2021-02-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20210224_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='商品敘述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='s_desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品簡述'),
        ),
    ]
