# Generated by Django 2.2.5 on 2021-02-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20210225_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='like',
            new_name='heart',
        ),
    ]
