# Generated by Django 2.2.5 on 2021-02-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20210225_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_pattern',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='商品型號'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='Images_url',
            field=models.ImageField(upload_to='static/upload/images/goods_min', verbose_name='圖片類型'),
        ),
    ]
