# Generated by Django 2.2.5 on 2021-03-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20210225_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='Images_url',
            field=models.ImageField(upload_to='static/upload/images/goods_min', verbose_name='商品圖片路徑'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='商品價格'),
        ),
        migrations.AlterField(
            model_name='shop_banner',
            name='Banner_Url',
            field=models.ImageField(upload_to='static/upload/images/Banners', verbose_name='Banner圖片路徑'),
        ),
        migrations.AlterField(
            model_name='shop_banner',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Banner名稱'),
        ),
    ]
