# Generated by Django 2.2.5 on 2021-04-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0016_auto_20210301_0902'),
        ('register', '0017_auto_20210416_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_user_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_color', models.CharField(max_length=10, verbose_name='商品顏色')),
                ('goods_size', models.CharField(max_length=4, verbose_name='商品尺寸')),
                ('goods_img_url', models.CharField(max_length=90, verbose_name='商品圖')),
                ('goods_amount', models.IntegerField(verbose_name='商品數量')),
                ('goods_price', models.IntegerField(verbose_name='商品價格')),
                ('goods_total_price', models.IntegerField(verbose_name='商品總價格')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Goods', verbose_name='商品id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_Member', verbose_name='用戶id')),
            ],
            options={
                'verbose_name': '各用戶購物車表',
                'verbose_name_plural': '各用戶購物車表',
                'db_table': 'Shop_user_cart',
            },
        ),
    ]
