# Generated by Django 2.2.5 on 2021-04-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0002_auto_20210418_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_user_cart',
            name='goods_color_img_url',
            field=models.CharField(max_length=50, null=True, verbose_name='商品顏色小圖路徑'),
        ),
    ]
