# Generated by Django 2.2.5 on 2021-04-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0004_auto_20210424_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_user_cart',
            name='goods_color_img_url',
        ),
    ]
