# Generated by Django 2.2.5 on 2021-05-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0002_order_info_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_info',
            name='order_check_time',
            field=models.DateField(null=True, verbose_name='訂單確認日期'),
        ),
    ]
