# Generated by Django 2.2.5 on 2021-05-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_system', '0004_auto_20210506_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='order_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='訂單編號'),
        ),
    ]
