# Generated by Django 2.2.5 on 2021-05-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0017_auto_20210416_2016'),
        ('shop_cart', '0006_pay_send'),
        ('index', '0016_auto_20210301_0902'),
        ('order_system', '0010_auto_20210506_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=20, verbose_name='收件人姓名')),
                ('recipient_phone_number', models.CharField(max_length=100, verbose_name='收件人電話')),
                ('recipient_address', models.CharField(max_length=100, verbose_name='寄送地址')),
                ('order_total_price', models.IntegerField(verbose_name='訂單金額')),
                ('order_time', models.DateField(verbose_name='訂單日期')),
                ('order_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='訂單編號')),
                ('order_status', models.BooleanField(default=False, verbose_name='訂單處理狀態')),
                ('order_check_time', models.DateField(null=True, verbose_name='訂單確認日期')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_cart.Pay_send', verbose_name='支付方式及運送方式')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_Member', verbose_name='用戶名稱')),
            ],
            options={
                'verbose_name': '用戶訂單',
                'verbose_name_plural': '用戶訂單',
                'db_table': 'Order_info',
            },
        ),
        migrations.CreateModel(
            name='Order_info_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_color', models.CharField(max_length=20, verbose_name='商品顏色')),
                ('goods_size', models.CharField(max_length=4, verbose_name='商品尺寸')),
                ('goods_img_url', models.CharField(max_length=100, verbose_name='商品圖')),
                ('goods_amount', models.IntegerField(verbose_name='商品數量')),
                ('goods_price', models.IntegerField(verbose_name='商品價格')),
                ('goods_total_price', models.IntegerField(verbose_name='商品總價格')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Goods', verbose_name='商品編號')),
                ('orders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_system.Order_info', verbose_name='訂單編號')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_Member', verbose_name='用戶名稱')),
            ],
            options={
                'verbose_name': '用戶訂單明細',
                'verbose_name_plural': '用戶訂單明細',
                'db_table': 'Order_info_detail',
            },
        ),
    ]
